---
title: "Subway Data"
author: "Amanda Rodriguez"
date: "July 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(readr)
library(tidyverse)
library(lubridate)
library(dplyr)
library(zoo)
library(glmnet)
library(broom)
library(rgeos)
library(tigris)
library(dplyr)
library(leaflet)
library(sp)
library(ggmap)
library(maptools)
library(httr)
library(rgdal)
library(RColorBrewer)

# load todd data
load("~/Microsoft DS3/project/project data/todd_subway_data.RData")
```

```{r}
# organize weather data and station level data 

# load station_data from mta
station_data <- read_csv("http://web.mta.info/developers/data/nyct/subway/Stations.csv")

# get stop_id and stop_name fields, and create a stop_id with N and S appended
station_data <- station_data %>% 
  rename(stop_id = `GTFS Stop ID`, stop_name = `Stop Name`, structure = `Structure`, 
         lat = `GTFS Latitude`, long = `GTFS Longitude`) %>%
  mutate(stop_id_N = sprintf('%sN', stop_id), stop_id_S = sprintf('%sS', stop_id)) %>%
  gather(`stop_id_N`, `stop_id_S`, key = "stop_ids", value = "stop_id") %>%
  select(stop_name, stop_id, structure, lat, long)

# https://www.ncdc.noaa.gov/cdo-web/datatools/lcd         hourly weather data
weather_2018 <- read_csv("~/Microsoft DS3/project/project data/weather_2018.csv") %>% 
  mutate(ymd = as.Date(DATE), hour = hour(DATE)) %>%
  select(ymd, DATE, hour, HOURLYPrecip)

# replace T's, remove "s" from the end of entries, and remove NA
weather_2018$HOURLYPrecip[weather_2018$HOURLYPrecip == "T"] <- "0.001" # T = trace amounts(drizzling)

weather_2018$HOURLYPrecip  <- gsub("[^0-9\\.]","",weather_2018$HOURLYPrecip) # s = suspected precip

weather_2018 <- weather_2018 %>% 
  group_by(ymd) %>% arrange(ymd, hour) %>% 
  mutate(HOURLYPrecip = na.approx(HOURLYPrecip, rule = 2)) %>%
  ungroup()

```

```{r}
# exp wait time for each station by station type for each day and hour
todd_subway_data <- 
  todd_subway_data[!(todd_subway_data$route_mta_id %in% c("GS","SS","FS","H","SI")), ] %>% # remove SI and shuttle trains
  mutate(ymd = as.Date(departure_time), hour = hour(departure_time), day = wday(departure_time))

todd_and_stop_normal <- left_join(todd_subway_data, station_data, by = c("stop_mta_id" = "stop_id")) %>%
  group_by(route_mta_id, stop_name) %>% 
  mutate(count = n ()) %>% 
  filter(count > 13000) %>% # get "normal" stops only
  ungroup()

exp_wait_time_by_station <- todd_and_stop_normal %>% 
  group_by(ymd, day, hour, route_mta_id, stop_mta_id) %>% 
  summarise(exp_wait = sum(seconds_until_next_departure^2)/(2*sum(seconds_until_next_departure))) %>%
  ungroup()

exp_wait_time_and_weather <- 
  left_join(exp_wait_time_by_station, weather_2018, by = c("ymd", "hour")) %>%
  left_join(station_data, by = c("stop_mta_id" = "stop_id"))
#  left_join(routes, by = c("route_mta_id" = "route_id"))

```

```{r}
# plot this one
# baseline model without precipitation 
#df <- exp_wait_time_and_weather %>% filter(month(ymd) == 4, day < 7 & day > 1, hour < 20 & hour > 6) %>% #select(stop_mta_id, route_mta_id, day, hour, exp_wait, HOURLYPrecip, structure)

# add station type
x <- sparse.model.matrix(exp_wait ~ as.factor(stop_mta_id) + 
                    as.factor(route_mta_id) + as.factor(day) + 
                    as.factor(hour), data = exp_wait_time_and_weather)
y <- exp_wait_time_and_weather$exp_wait


model <- glmnet(x, y, alpha = 0 , lambda = 0) # > 7 mins with full df  ~1-2 mins april df
#coef(model) #lambda.min for cv

model_df <- tidy(model)

model_df$term  <- gsub("[as.factor(stop_mta_id)]*","",model_df$term)

model_df <- model_df %>% arrange(desc(estimate)) 

model_df$term  <- substring(model_df$term, 1, 4) 

model_df <- left_join(model_df, station_data, by = c("term" = "stop_id")) %>% na.omit()
```

```{r}
# map plot of exp wait without rain in the model
#ggplot(aes(x = estimate), data = model2_df) + 
#  geom_histogram() + 
#  xlim(-175, 175)


clrs <- brewer.pal(5, "RdYlGn")

pal <- colorNumeric(
  palette = clrs,
  domain = model_df$estimate,
  reverse = TRUE)


leaflet(model_df) %>%
  addTiles() %>%
  setView(-73.9124206, 40.737, zoom = 11) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircleMarkers(~long, ~lat,
                   popup = paste("<b>", model_df$stop_name, "</b>",
                                 "<br/>", round(model_df$estimate/60, 2), "mins"),
                   radius = 5,
                   color = ~pal(estimate),
                   stroke = FALSE, 
                   fillOpacity = 0.5)
```


```{r}
# interaction of stop with log(precip)

x1 <- sparse.model.matrix(exp_wait ~ as.factor(stop_mta_id)*log(HOURLYPrecip + 1) + 
                    as.factor(route_mta_id) + as.factor(day) + 
                    as.factor(hour), data = exp_wait_time_and_weather)

model1 <- glmnet(x1, y, alpha = 0 , lambda = 0) 
#model1_df <- tidy(model1)

#exp_wait_time_and_weather$model1 <- predict(model1, newx = exp_wait_time_and_weather)
```

```{r}
# plot this one
# interaction of stop with precip 
x2 <- sparse.model.matrix(exp_wait ~ as.factor(stop_mta_id)*HOURLYPrecip + 
                    as.factor(route_mta_id) + as.factor(day) + 
                    as.factor(hour), data = exp_wait_time_and_weather)

model2 <- glmnet(x2, y, alpha = 0 , lambda = 0)
model2_df <- tidy(model2)

model2_df$term  <- gsub("[as.factor(stop_mta_id)]*","",model2_df$term)

model2_df <- model2_df %>% arrange(desc(estimate)) 

model2_df$term  <- substring(model2_df$term, 1, 4) 

model2_df <- left_join(model2_df, station_data, by = c("term" = "stop_id")) %>% na.omit()

```

```{r}
# new df to predict mon at 9am affect

mon_nine <- exp_wait_time_and_weather %>% select(route_mta_id, stop_mta_id, day, hour, HOURLYPrecip) %>% filter(day == 2, hour == 9, HOURLYPrecip == 0) %>% arrange(stop_mta_id) %>% distinct()
# predict(model2, newx = mon_nine, s=lambda.min)
```

```{r}

# map plot of stops interacted with precip


model2_df$estimate <- pmin(model2_df$estimate, quantile(model2_df$estimate, 0.9))

model2_filtered <- model2_df %>% filter(estimate > 0)

clrs <- brewer.pal(5, "RdYlGn")

pal <- colorNumeric(
  palette = clrs,
  domain = model2_filtered$estimate,
  reverse = TRUE)


leaflet(model2_filtered) %>%
  addTiles() %>%
  setView(-73.9124206, 40.737, zoom = 11) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircleMarkers(~long, ~lat,
                   popup = paste("<b>", model2_filtered$stop_name, "</b>",
                                 "<br/>", round(model2_filtered$estimate/60, 2), "mins"),
                   radius = 5,
                   color = ~pal(estimate),
                   stroke = FALSE, 
                   fillOpacity = 0.5)



```

