---
title: "Map With K Shortest Paths"
author: "Graph Team"
date: "July 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Sasha, Ayliana, Brian, & Taxi*  

#### Load libraries
```{r}
library(tidyverse)
library(igraph)
library(lubridate)
source('../../src/taxi/Util/read.R')
source('../../src/taxi/Util/translate.R')
```

#### Load data
```{r}

source('../../src/taxi/Util/time.R')
load.mult('../../data/taxi_cleaned/')
load('../../data/todd_subway_realtime.RData')

```

#### Filtering
```{r}

#All Service
time_filter <- seq(0, 23)
day_filter <- c("Weekday", "Saturday", "Sunday")

#Ordinary Service
# time_filter <- seq(6, 23)
# day_filter <- c("Weekday")

#Weekend Service
#time_filter <- seq(6, 23)
#day_filter <- c("Saturday", "Sunday")

#Late Night Service
#time_filter <- seq(0, 5)
#day_filter <- c("Weekday", "Saturday", "Sunday")
```
```{r}
#cut off paths
paths.filtered <- paths %>% filter(relative_popularity > .1) %>% .$path_id
edges.filtered <- trip_edges %>% translate(trips, trip_id, path_id, trip_id = path_id) %>% filter(path_id %in% paths.filtered)
```
#### Formatting static
```{r}
#trips$route_id <- as.character(trips$route_id)


# all scheduled trips
#all_trips <- stop_times %>%
#  filter(!is.na(arrival_time)) %>%
#  left_join(stops) %>%
#  extract(trip_id, c("route_id"), regex=".*_.*_(.*)\\.\\..*", remove=FALSE) %>%
#  extract(trip_id, c("day_of_week"), regex=".*-.*-(.*)-.*", remove=FALSE) %>%
#  extract(trip_id, c("time"), regex=".*-.*-.*-.*_(.*)_.*\\.\\..*", remove=FALSE) %>%
#  mutate(stop_id = substr(stop_id, 1, 3),
#         prev_stop_id = ifelse(trip_id == lag(trip_id), lag(stop_id), NA),
#         prev_stop_name = ifelse(trip_id == lag(trip_id), lag(stop_name), NA),
#         trip_start_time = seconds_to_period(as.numeric(time)*.6),
#         trip_start_time = as.POSIXct(sprintf("%s:%s:%s", 
#                                              hour(trip_start_time), minute(trip_start_time), second(trip_start_time)),
#                                      "%H:%M:%S", tz="America/New_York")) %>%
 # left_join(trips) %>%
 # select(route_id, trip_id, direction_id, day_of_week, trip_start_time, arrival_time, departure_time, 
  #       stop_id, stop_name, prev_stop_id, prev_stop_name)

all_trips <- edges.filtered %>% 
  translate(trips, trip_id, c(route_id, day_type,direction_id, first_arrival_time), 
            trip_id = c(route_id, day_of_week, direction_id, trip_start_time)) %>%
  select(route_id, trip_id, direction_id, day_of_week, trip_start_time, arrival_time, departure_time, 
         prev_stop_id =stop_id.u, stop_id = nxt.stop_id.u) %>%
  translate(stops, stop_id, stop_name, stop_id = stop_name, prev_stop_id = prev_stop_name) %>%
  mutate(trip_start_time = as.timeStr(trip_start_time)) %>%
  ungroup()
```

#### Transfer
```{r}
# unique trip sequences by line
unique_sequences <- all_trips %>%
  filter(hour(hms(trip_start_time)) %in% time_filter) %>%
  filter(day_of_week %in% day_filter) %>%
  select(route_id, stop_id, stop_name, prev_stop_id, prev_stop_name, direction_id) %>%
  distinct 


# prepping the transfer data
transfer_sequences <- transfer %>% translate(stops, stop_id, stop_name, from_stop_id = prev_stop_name, to_stop_id = stop_name) %>%
  rename(stop_id = to_stop_id, prev_stop_id = from_stop_id) %>% 
  mutate(route_ids = "T", weight = min_transfer_time, sd = NA, lower_quartile = NA, median = NA, upper_quartile = NA,
         direction_id = NA) %>%
  select(route_ids,stop_id, prev_stop_id, stop_name, prev_stop_name,direction_id, weight, sd, lower_quartile, median, upper_quartile)
```

#### Realtime Formatting
```{r}
realtime <- realtime %>%
  mutate(day_of_week = weekdays(departure_time),
         day_of_week = ifelse(!day_of_week %in% c("Saturday","Sunday"),"Weekday", day_of_week))
```

#### Get weights for the connections between stations
```{r weights, warning=FALSE}

station_weights <- realtime %>% mutate(stop_mta_id = substr(stop_mta_id,1,nchar(stop_mta_id)-1)) %>% 
  arrange(realtime_trip_id, departure_time) %>% 
  group_by(realtime_trip_id) %>% mutate(departure_time_prev = lag(departure_time), prev_stop_mta_id = lag(stop_mta_id)) %>% 
  filter(!is.na(prev_stop_mta_id)) %>% mutate(travel_time = departure_time - departure_time_prev) %>%
  group_by(stop_mta_id, prev_stop_mta_id) %>% 
  summarize(weight = mean(travel_time), sd = sd(travel_time, na.rm=TRUE),
            lower_quartile = quantile(travel_time, 0.25),
            median = median(travel_time), upper_quartile = quantile(travel_time,
                                                                    0.75))
```

#### Combine station ids
```{r}
station_route_ids <- unique_sequences %>% select(route_id, stop_id, prev_stop_id) %>% 
  group_by(stop_id, prev_stop_id) %>% summarize(route_ids = paste0(route_id, collapse = '_'))
```

#### Combine realtime with static edges
```{r}
## Static with realtime weights and route_ids
station_weights <- station_weights %>% ungroup() %>% mutate(route_mta_id = as.character(route_mta_id)) 
full_sequences <- unique_sequences %>%
  left_join(station_weights, by = c("stop_id" = "stop_mta_id", "prev_stop_id" =
                              "prev_stop_mta_id"))%>%
  left_join(station_route_ids, by = c("stop_id", "prev_stop_id")) 

#merge remove duplicates
full_sequences <- full_sequences %>% select(-route_id) %>% distinct
  
#Transfers already has weights from the min_transfer_time field (now renamed weight) so we rbind the two sequence objects
full_sequences <- rbind(full_sequences, transfer_sequences)

#full_sequences %>% filter(stop_id == 'R11') %>% View
```

#### Make an igraph
```{r igraph}
library(igraph)
theme_set(theme_bw())

# Input a dataframe of the edges that exist between stops, with weight as an attribute
igraph_edges <- full_sequences %>%
  filter(!is.na(prev_stop_id), !is.na(weight)) %>%
  select(prev_stop_id, stop_id, weight, route_ids, direction_id)

mta_igraph <- graph.data.frame(igraph_edges, directed=TRUE)

```

#### Function to find shortest k paths
```{r k_shortest_function}

##################
# Helper Functions
##################

# Determine if a given path variant has already been seen
contains.path <- function(variants, variant){
  return( any( unlist( lapply( variants, function(x){ identical(unlist(x$variant$vert),unlist(variant)) } ) ) ) )
}

# Choose shortest path variant
select.shortest.path <- function(variants){
  return( which.min( unlist( lapply( variants, function(x){x$variants$dist} ) ) ) )
}

# Return all variants of a given path
calculate.variants <- function(variants, variant, from, to, gmode){
  # Take graph from current path
  g <- variant$g
  
  # Iterate through edges, removing one each iterations
  for (j in unlist(variant$path)){
    newgraph <- delete.edges(g, j) # Remove edge
    sp <- get.shortest.paths(newgraph,from,to, output='both', mode=gmode) # Calculate shortest path
    spd <- shortest.paths(newgraph,from,to,mode=gmode) # Calculate length
    if (spd != Inf){ # The the path is found
      if (!contains.path(variants, sp$vpath)) # Add to list, unless it already contains the same path
      {
        variants[[length(variants)+1]] <- list(g=newgraph, variants=list(path=sp$epath, vert=sp$vpath, dist=spd))
      }
    }
  }
  return(variants)
}

######################
# Main K Path Function
######################

k.shortest.paths <- function(graph, from, to, k, gmode){
  # First shortest path
  k0 <- get.shortest.paths(graph,from,to, output='both', mode=gmode)
  
  # Number of currently found shortest paths
  kk <- 1
  
  # List of alternatives
  variants <- list()
  
  # Shortest variants
  shortest.variants <- list(list(g=graph, path=k0$epath, vert=k0$vpath, dist=shortest.paths(graph,from,to,mode=gmode)))
  
  # Until k shortest paths are found
  while(kk<k){
    # Take last found shortest path
    last.variant <- shortest.variants[[length(shortest.variants)]]              
        
    # Calculate all alternatives
    variants <- calculate.variants(variants, last.variant, from, to, gmode)
        
    # Find shortest alternative
    sp <- select.shortest.path(variants)
    
    # Add to list, increase kk, remove shortest path from list of alternatives
    shortest.variants[[length(shortest.variants)+1]] <- list(g=variants[[sp]]$g, path=variants[[sp]]$variants$path, vert=variants[[sp]]$variants$vert, dist=variants[[sp]]$variants$dist)
    kk <- kk+1
    variants <- variants[-sp]
  }
  return(clean_output(shortest.variants))
}

```


#### Clean output from k shortest paths
```{r k_shortest, warning=FALSE}

clean_output <- function(k_shortest){
  
  shortest_routes <- setNames(data.frame(matrix(ncol = 4, nrow = 0)),
                              c("itinerary_id", "line", "station","direction"))
  route <- vector(mode = "character")
  
  #loop through itineraries
  for(i in 1:k_num){
    station_list <- names(unlist(k_shortest[[i]]$`vert`))
    line_ids <- edge.attributes(mta_igraph, index =
                                unlist(k_shortest[[i]]$`path`))$route_ids
    prev_line_ids <- str_split(line_ids[1], "_")[[1]]
    r = 0
    
    #loop through stations
    for (j in 1:length(station_list)){
      shortest_routes <- shortest_routes %>% 
        add_row(itinerary_id = i, line =line_ids[j], 
                station = station_list[j], direction = "N")
      
      #Split line ids into a list
      cur_line_ids <- str_split(line_ids[j], "_")[[1]]
      intersect_lines <- intersect(cur_line_ids, prev_line_ids)
      
      #Check if you need to transfer
      if (length(intersect_lines) == 0){
        if("T" %in% cur_line_ids){
          #Set intersect_lines to next line_ids
          intersect_lines <-  str_split(line_ids[j+1], "_")[[1]]
        }
        else{
          #Otherwise set to current line_ids
          intersect_lines <- cur_line_ids
        }      
        route <- append(route, rep(paste(prev_line_ids, collapse = "_"), r))
        r = 0
      }
      r = r+1
      prev_line_ids <- intersect_lines
    }
    route <- append(route, "END")
  }
  shortest_routes$line <- route
  
  return(shortest_routes)
}
```

#### Test
```{r}
k_num <- 3
#Find k_num shortest paths leading going from stop R13 to stop D05 
#629 415
k_shortest <- k.shortest.paths(mta_igraph, from = "415", to = "D13", k=k_num, gmode="out")

t<- k_shortest %>% group_by(itinerary_id) %>% mutate(prev.line=lag(line), prev.station = lag(station)) %>% mutate(lineChange = line != prev.line) %>% ungroup %>% mutate(rowId = 1:nrow(.), type = 'Travel')

change_indices <- t[,c('line','lineChange',"rowId")] %>% filter(lineChange == T, line != 'END') %>% .$rowId

t.1 <- t[change_indices,] %>% select(itinerary_id, station, direction, rowId) %>% mutate(rowId = rowId-.5)
t.2 <- t[change_indices-1,] %>% select(line,rowId) %>% mutate(rowId = rowId+.5)
t.3 <- left_join(t.1, t.2, by='rowId') %>% mutate(type = 'start_transfer')
rbind(t %>% select(itinerary_id, line,station, direction, rowId,type), t.3) %>% arrange(rowId) %>% mutate(rowId = 1:nrow(.)) %>% View


z <- data.frame(d=1:3)
name_list <- c('A','B','C')
col_list <- c('start','end')
for (i in name_list){
  for (j in col_list) z[[paste(i,j,sep='.')]] <- c(1,2,3)
}


get_itinerary <- function(shortest_paths_df, num_ititeraries) {
 
 itinerary <- setNames(data.frame(matrix(ncol = 6, nrow = 0)),
                             c("itinerary_id", "station", "line", "direction", "leg", "event"))
 
 # format each itinerary_id separately
 for (i in 1:num_ititeraries) {
   df <- shortest_paths_df %>%
     filter(itinerary_id == i)
   
   # current index
   k = 1
   
   # keep track of leg
   l = 1
   
   df <- df %>% mutate(leg = l, event = "travel")
   df$event[1] <- "start_trip"
   
   while (k < nrow(df)){
     # next index
     j = k+1
     
     # identify transfers
     if (df$station[k] != df$station[j] & df$line[k] != df$line[j]) {
       
       # identify an 'implicit transfer (e.g. transfer 120->120 from 1 to 2/3)
       if (df$line[j] != "") {
         df <- df %>% add_row(itinerary_id = df$itinerary_id[j], station = df$station[j],
               line = df$line[k], direction = df$direction[k], leg = l, .after = k)
       }
       
       
       # identify an 'explicit' transfer (e.g. transfer R11->629 from N/R to 4)
       else {
         df$line[j] <- df$line[k]
         df$leg[j] <- df$leg[k]
       }
       
       df$event[j] <- "start_transfer"
       df$event[j+1] <- "end_transfer"
       df$direction[j] <- df$direction[k]
       
       l = l+1
       k = k+1
     }
     
     k = k+1
     df$leg[k] <- l
     
   }
   
   df <- df[1:nrow(df)-1,]
   df$event[nrow(df)] <- "end_trip"
 
   itinerary <- rbind(itinerary, df)
 }
   return(itinerary)
}
clean_output <- function(k_shortest){
 
 shortest_routes <- setNames(data.frame(matrix(ncol = 4, nrow = 0)),
                             c("itinerary_id", "station", "line", "direction"))
 route <- vector(mode = "character")
 
 #loop through itineraries
 for(i in 1:k_num){
   station_list <- names(unlist(k_shortest[[i]]$`vert`))
   line_ids <- edge.attributes(mta_igraph, index =
                               unlist(k_shortest[[i]]$`path`))$route_ids
   prev_line_ids <- str_split(line_ids[1], "_")[[1]]
   dirs <- edge.attributes(mta_igraph, index =
                               unlist(k_shortest[[i]]$`path`))$direction_id

   r = 0
   #loop through stations
   for (j in 1:length(station_list)){
     
     shortest_routes <- shortest_routes %>%
       add_row(itinerary_id = i, line =line_ids[j],
               station = station_list[j], direction = dirs[j])
     
     #Split line ids into a list
     cur_line_ids <- str_split(line_ids[j], "_")[[1]]
     intersect_lines <- intersect(cur_line_ids, prev_line_ids)
     
     #Check if you need to transfer
     if (length(intersect_lines) == 0 | "T" %in% cur_line_ids){
       
       if("T" %in% cur_line_ids){
 
         #Set intersect_lines to next line_ids
         # intersect_lines <-  str_split(line_ids[j-1], "_")[[1]]
         shortest_routes[j,]$direction <- shortest_routes[j-1,]$direction
       }

       else{
         #Otherwise set to current line_ids
         intersect_lines <- cur_line_ids
       }
     
       route <- append(route, rep(paste(prev_line_ids, collapse = "_"), r))
       r = 0

     } # endif

     r = r+1
     prev_line_ids <- intersect_lines
     
   } # endforj
   route <- append(route, "END")

   
 } # endfori
 
 shortest_routes$line <- route
 # shortest_routes$event <- event_type
 
 return(shortest_routes)
}
get_itinerary(k_shortest,3) %>% View
```

```{r}
clean_output <- function(k_shortest){
 
 shortest_routes <- setNames(data.frame(matrix(ncol = 4, nrow = 0)),
                             c("itinerary_id", "station", "line", "direction"))
 route <- vector(mode = "character")
 
 #loop through itineraries
 for(i in 1:k_num){
   station_list <- names(unlist(k_shortest[[i]]$`vert`))
   line_ids <- edge.attributes(mta_igraph, index =
                               unlist(k_shortest[[i]]$`path`))$route_ids
   prev_line_ids <- str_split(line_ids[1], "_")[[1]]
   dirs <- edge.attributes(mta_igraph, index =
                               unlist(k_shortest[[i]]$`path`))$direction_id

   r = 0
   #loop through stations
   for (j in 1:length(station_list)){
     
     shortest_routes <- shortest_routes %>%
       add_row(itinerary_id = i, line =line_ids[j],
               station = station_list[j], direction = dirs[j])
     
     #Split line ids into a list
     cur_line_ids <- str_split(line_ids[j], "_")[[1]]
     intersect_lines <- intersect(cur_line_ids, prev_line_ids)
     
     #Check if you need to transfer
     if (length(intersect_lines) == 0 | "T" %in% cur_line_ids){
       
       if("T" %in% cur_line_ids){
 
         #Set intersect_lines to next line_ids
         # intersect_lines <-  str_split(line_ids[j-1], "_")[[1]]
         print('start')
         shortest_routes[j,]$direction <- shortest_routes[j-1,]$direction
         print('end')
       }

       else{
         #Otherwise set to current line_ids
         intersect_lines <- cur_line_ids
       }
     
       route <- append(route, rep(paste(prev_line_ids, collapse = "_"), r))
       r = 0

     } # endif

     r = r+1
     prev_line_ids <- intersect_lines
     
   } # endforj
   route <- append(route, "END")

   
 } # endfori
 
 shortest_routes$line <- route
 # shortest_routes$event <- event_type
 
 return(shortest_routes)
}
```