---
title: "Subway Data"
author: "Amanda Rodriguez"
date: "July 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(readr)
library(tidyverse)
library(lubridate)
library(dplyr)
library(igraph)

# todd_subway_data <- read_csv("MTA Data/todd_subway_data.csv", col_types = cols(route_mta_id = col_factor(levels = NULL)))
# save(todd_subway_data, file = "todd_subway_data.RData")
load("~/Microsoft DS3/project/project data/todd_subway_data.RData")
```

```{r}
# load station_data from mta
station_data <- read_csv("http://web.mta.info/developers/data/nyct/subway/Stations.csv")

# get stop_id and stop_name fields, and create a stop_id with N and S appended
station_data <- station_data %>% 
  rename(stop_id = `GTFS Stop ID`, stop_name = `Stop Name`) %>%
  mutate(stop_id_N = sprintf('%sN', stop_id), stop_id_S = sprintf('%sS', stop_id)) %>%
  gather(`stop_id_N`, `stop_id_S`, key = "stop_ids", value = "stop_id") %>%
  select(stop_name, stop_id)

todd_and_stop_data <- left_join(todd_subway_data, station_data, by = c("stop_mta_id" = "stop_id"))

# https://www.ncdc.noaa.gov/cdo-web/datatools/lcd hourly weather data
weather_2018 <- read_csv("~/Microsoft DS3/project/project data/weather_2018.csv") %>% 
  mutate(ymd = as.Date(DATE)) %>%
  select(ymd, DATE, HOURLYPrecip)
```

```{r}
# exp wait time for each station for (each hour on) every day
todd_and_stop_data <- 
  todd_and_stop_data[!(todd_and_stop_data$route_mta_id %in% c("GS","SS","FS","H","SI")), ] %>%
  mutate(ymd = as.Date(departure_time), hour = hour(departure_time), day = wday(departure_time))
  
todd_and_stop_normal <- todd_and_stop_data %>% 
  group_by(route_mta_id, stop_name) %>% 
  mutate(count = n ()) %>% 
  #filter(count > 13000) %>% # get "normal" stops only
  ungroup() 

exp_wait_time_by_station <- todd_and_stop_normal %>% 
  group_by(ymd, day, stop_name, route_mta_id) %>% #changing group by to include or remove hour if we want expected wait times by day or by hour
  summarise(exp_wait = sum(seconds_until_next_departure^2)/(2*sum(seconds_until_next_departure))) %>%
  ungroup()

exp_wait_time_and_weather <- left_join(exp_wait_time_by_station,weather_2018, by = c("ymd" = "ymd")) #%>%
#  left_join(station_data, by = c("stop_mta_id" = "stop_id"))

```

```{r}
# no relationship between SNOW/ PRCP and expected wait (by day)
# no difference between above and below ground (OR SO WE THOUGHT! UPDATE AT 5:30PM AFTER CORRELATIONS WERE MADE IN BRIAN'S NOTEBOOK)
exp_wait_time_and_weather %>% 
  filter(route_mta_id == "2") %>%
  ggplot(aes(x = HOURLYPrecip, y = exp_wait)) + 
  geom_point()  +
  geom_smooth() +
  facet_wrap(~stop_name) 
```

```{r}
exp_wait_time_by_station <- todd_and_stop_normal %>% 
  group_by(ymd, day, hour, stop_mta_id, route_mta_id) %>% #changing group by to include or remove hour if we want expected wait times by day or by hour
  summarise(exp_wait = sum(seconds_until_next_departure^2)/(2*sum(seconds_until_next_departure))) %>%
  ungroup()

exp_wait_time_and_weather <- left_join(exp_wait_time_by_station,weather_2018, by = c("ymd" = "ymd"))

exp_wait_time_and_weather %>% 
  filter(route_mta_id == "2") %>%
  ggplot(aes(x = hour, y = exp_wait)) + 
  geom_smooth()  +
  facet_wrap(~day) +
  xlim(7,20)
```
