---
title: "LGA Heatmap"
author: "Sasha, Ayliana, Taxi"
date: "August 3, 2018"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#### Load libraries
```{r warning=FALSE, message=FALSE}
library(igraph)
library(leaflet)
library(RColorBrewer)
library(geosphere)
library(sp)
library(maptools)
library(broom)
library(httr)
library(rgdal)
library(ggmap)
library(KernSmooth)
library(ggplot2)
library(gstat)
library(raster)
library(mapview)
library(tidyverse)
```

#### Load data
```{r load data}
# load('../../data/reverse_mta_igraph_rush_hour.RData')
stops <- read_csv('../../data/google_transit_subway_static/stops.txt')
stops <- stops %>% dplyr::select(stop_id, stop_lat, stop_lon, stop_name)
load('../../data/at_igraph_edges.rdata')
source('../../src/path_finding.R')
load('../../data/wait_times_rush_hour.rdata')
```

#### distance function
```{r}
distance <- function(graph, path) sum(E(graph, path=path)$weight)
```

#### geodistance (in km)
```{r}
Distance <- function(LatA, LonA, LatB, LonB){
  scaling_factor <- 110.25
  x <- LatA - LatB
  y <- (LonA - LonB) * cos(40.75 * (pi)/180)

  return (scaling_factor*sqrt(x * x + y * y))

}
```

#### Find shortest paths from _____
```{r regular}
dest <- "LGA"

at_igraph_edges <- mutate(at_igraph_edges, 'weight' = `90%`)
at_igraph_edges$weight = as.numeric(at_igraph_edges$weight)
at_graph <-graph.data.frame(at_igraph_edges)


map_data <- get.all.shortest.paths(at_graph, dest, mode = "out")

map_data <- map_data$res %>% lapply(function(x)data.frame(stop_id = names(x)[length(x)], distance <- distance(at_graph, x), path = paste0(names(x), collapse = '>'))) %>%
  reduce(rbind) 

stops <- stops %>%
  add_row(stop_id = "LGA", stop_lat = 40.7769271, stop_lon = -73.87396590000003, stop_name  = "LaGuardia Airport") %>%
  add_row(stop_id = "JFK", stop_lat = 40.6413, stop_lon = -73.7781, stop_name = "John F. Kennedy International Airport")

map_data <- map_data %>% left_join(stops)
names(map_data) <- c("stop_id", "distance", "path", "stop_lat", "stop_lon", "stop_name")

map_data <- map_data %>% 
  left_join(wait_times_filter, by = c("stop_id" = "stop_mta_id")) %>% 
  mutate(wait_time_median = ifelse(is.na(wait_time_median), 0, wait_time_median),
         wait_time_90 = ifelse(is.na(wait_time_90), 0, wait_time_90))  %>%
  mutate(distance = distance + wait_time_90)

    
map_data <- map_data %>%
  mutate(subway_mins = round(distance/60, 2))


```

#### Create a grid of points
```{r make-grid}
grid_lats <- seq(min(stops$stop_lat), max(stops$stop_lat), by=0.002)
grid_lons <- seq(min(stops$stop_lon), max(stops$stop_lon), by=0.002)
grid <- expand.grid(grid_lats, grid_lons) %>%
    dplyr::select(lat = Var1, lon = Var2)
```


#### Get subway travel time, walking time, total time
##### Filter for points reachable within 20 mins of walking
```{r get-times}
total_time = vector()
walking = vector()
station = vector()
for(i in 1:nrow(grid)){
 result<- map_data %>% mutate(walking_time = 720*Distance(grid$lat[i], grid$lon[i], stop_lat, stop_lon), 
                              total_time = (walking_time + distance))
 idx <- which.min(result$total_time)

 total_time[i] <- result[idx, "total_time"]
 walking[i] <- result[idx, "walking_time"]
 station[i] <- result[idx, "stop_name"]
 # print(walking[i])
}
grid$time <- total_time
grid$walking <- walking
grid$nearest_stop <- station
grid <- grid %>% mutate(total_time_mins = round(time/60, 2), walking_mins = round(walking/60, 2), subway_mins = total_time_mins - walking_mins)
grid$log_mins <- log(grid$total_time_mins)

```



### **Heatmap with raster layer**
```{r}


r <- GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
nyc_neighborhoods <- readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)


filtered_grid <- grid %>%
  filter(walking_mins <= 20) %>%
  mutate(min_interval = cut(total_time_mins, seq(0, max(total_time_mins), by = 5), include.lowest = TRUE),
         bin = cut(total_time_mins, seq(0, max(total_time_mins), by = 5), include.lowest = TRUE, labels = FALSE))

filtered_grid_spdf <- filtered_grid
coordinates(filtered_grid_spdf) <- ~lon + lat
proj4string(filtered_grid_spdf) <- proj4string(nyc_neighborhoods)
matches <- over(filtered_grid_spdf, nyc_neighborhoods)
filtered_grid <- cbind(filtered_grid, matches)
filtered_grid <- filtered_grid %>%
  filter(!is.na(neighborhood))

coords <- filtered_grid[c("lon", "lat")]

gridded(filtered_grid_spdf) <- TRUE


plot(filtered_grid_spdf, cex = 0.2, col = "grey")

points(coords, pch =1, col = "black", cex = 0.1)

#Interpolate surface and fix the output
idw <- idw(formula=total_time_mins ~ 1, locations=filtered_grid_spdf, newdata = filtered_grid_spdf)  # apply idw model for the data

residual_grid <- raster(idw, "var1.pred")
contourr <- rasterToContour(residual_grid)


rr <- mask(residual_grid, nyc_neighborhoods)
crs(rr) <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")



grid_pal <- colorNumeric(
  palette = c('#000000','#ff0000','#ffff00', '#008000'),
  domain = seq(0,140,20),
  reverse = TRUE,
  na.color = "transparent")




m <- leaflet(nyc_neighborhoods) %>% 
  addTiles() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  setView(-73.85, 40.75, zoom = 10.5) %>%
  addCircleMarkers(data = map_data, lng = ~stop_lon, lat = ~stop_lat,
                   color = ~grid_pal(subway_mins),
                   popup = paste("<b>", map_data$stop_name, "</b>", "<br/>",
                                 "subway:", map_data$subway_mins, "mins", "<br/>"),
                   radius = 4, stroke = FALSE, fillOpacity =0.9) %>%
  addMarkers(lat = 40.7769271, lng = -73.87396590000003) %>%
  addLegend("bottomright", pal = grid_pal, values = map_data$subway_mins,
    title = paste("Commute time to LaGuardia Airport", "<br/>", "(with proposed AirTrain)"),
    labFormat = labelFormat(suffix = " mins", transform = function(x) x),
    opacity = 1) %>%
  addRasterImage(rr, color=grid_pal, opacity = 0.4)
  
m


mapview::mapshot(m, url = here::here("figures", "lga_heatmap.html"), file = here::here("figures", "lga_heatmap.png"))
  

```


