---
title: "My Commute (07.09.18)"
author: "Akbar Mirza"
date: "July 10, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
commute <- read.csv("akbar-commute-070918.csv")
```

## Clean & Parse Commute Data

Correct for R defaults turning times into factors, and convert them to `POSIXct`.

```{r clean-commute-data}
commute <- commute %>% mutate(train_arrived_time = as.POSIXct(strptime(sprintf("2018-07-09 %s", actual_arrival), format = "%Y-%m-%d %H:%M"), tz = "America/New_York"))
commute <- commute %>% mutate(train_departed_time = as.POSIXct(strptime(sprintf("2018-07-09 %s", actual_departure), format = "%Y-%m-%d %H:%M"), tz = "America/New_York"))
commute <- commute %>% mutate(scheduled_departure_time = as.POSIXct(strptime(sprintf("2018-07-09 %s", scheduled_departure), format = "%Y-%m-%d %H:%M"), tz = "America/New_York"))

commute <- commute %>% select(station, line, schedule_depart = scheduled_departure_time, actual_depart = train_departed_time, actual_arrive = train_arrived_time, was_delayed, delay_reason, ride_event)
commute
```

## Gather Subway Feed Data

Use GTFS data to gather information about train trips

```{r subway-trip-data}
subway_070918 <- read.csv("todays_subway_data_feed_1.csv")

# gather station information
stop_data <- read_csv("http://web.mta.info/developers/data/nyct/subway/Stations.csv")

stop_data <- stop_data %>%
  mutate(stop_id_south = sprintf("%sS", `GTFS Stop ID`)) %>%
  select(stop_id = `GTFS Stop ID`, stop_id_south, stop_name = `Stop Name`)
  
# clean subway data
clean_data <- subway_070918 %>%
  mutate(min_time = as.POSIXct(minimum_time, tz = "America/New_York", origin = "1970-01-01"),
         max_time = as.POSIXct(maximum_time, tz = "America/New_York", origin = "1970-01-01"),
         info_time = as.POSIXct(latest_information_time, tz = "America/New_York", origin = "1970-01-01")) %>%
  select(X, trip_id, route_id, action, min_time, max_time, stop_id, info_time)

# join station data and trip data
data_with_stations <- left_join(clean_data, stop_data, by=c("stop_id"="stop_id_south"))

# find the trip id of my trip
my_trip_id <- data_with_stations %>%
  filter(stop_name == "Woodlawn" &
           hour(min_time) == 9 &
           minute(min_time) >= 35 &
           minute(min_time) <= 45) %>%
  select(trip_id) %>% first()

# get time I pulled in to Union Sq
last_arrival <- data_with_stations %>%
  filter(trip_id == my_trip_id & stop_id == "635S") %>%
  select(min_time) %>% first()

# my commute
data_with_stations %>% filter(trip_id == my_trip_id, min_time <= last_arrival)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
