---
title: "20180709_finding_commute_ayliana"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

##Load and clean mta data
```{r load and clean mta data, message = FALSE, warning = FALSE}
mta_data <- read_csv("feed_1_20180709_to_20180710.csv")
mta_data <- mta_data %>% mutate("min_time" = as.POSIXct(minimum_time, tz = "America/New_York", origin = "1970-01-01"), 
"max_time" = as.POSIXct(maximum_time, tz = "America/New_York", origin = "1970-01-01"),
"latest_time" = as.POSIXct(latest_information_time, tz = "America/New_York", origin = "1970-01-01"))

#get station names
station_data <- read_csv("http://web.mta.info/developers/data/nyct/subway/Stations.csv")
station_data <- station_data %>%
  select(stop_id = `GTFS Stop ID`, stop_name = `Stop Name`) %>%
  mutate(stop_id_south = sprintf("%sS", stop_id)) 

#join station names
filtered_data <- left_join(mta_data, station_data, by=c("stop_id"="stop_id_south"))
```

##Load and clean my commute data
```{r load and clean my commute data, message = FALSE}
commute <- read_csv("20180709_commute_ayliana.csv")
commute <- commute %>% mutate(train_arrived_time = as.POSIXct(sprintf("2018-07-09 %s", train_arrived), tz = "America/New_York"))
```

##Find my commute
```{r find commute, message= FALSE}
myTrip <- filtered_data %>% inner_join(commute, by = c("stop_name" = "station")) %>% filter(trip_id == "055800_1..S03R" & minimum_time >= 1531145443)
knitr::kable(myTrip)
```
