---
title: "20180712_mta_triptime_distribution"
author: "Phoebe Nguyen"
date: "July 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(ggthemes)

# load todd's subway_data
#setwd("~/nyctransit/notes/20180711")
load(file = "../../data/todd_subway_realtime.RData")

# load stop_times from GTFS Static
stop_times <- read_csv("../../data/google_transit_subway_static/stop_times.txt")

# load station_data from mta
station_data <- read_csv("http://web.mta.info/developers/data/nyct/subway/Stations.csv")

# get stop_id and stop_name fields, and create a stop_id with N and S appended
station_data <- station_data %>% group_by(`GTFS Stop ID`, `Stop Name`) %>%
  select(stop_id = `GTFS Stop ID`, stop_name = `Stop Name`) %>%
  mutate(stop_id_N = sprintf('%sN', stop_id), stop_id_S = sprintf('%sS', stop_id)) %>%
  gather(`stop_id_N`, `stop_id_S`, key = "stop_ids", value = "stop_id") %>%
  select(stop_name, stop_id)
```
## Getting Station Information

```{r getting-station-info}
# Generate edges between stations
trips <- stop_times %>% extract(trip_id, "route", regex=".*_.*_(.*)\\.\\..*", remove = FALSE)
trip_edges <- trips %>% mutate(prev_stop_id = ifelse(lag(trip_id) == trip_id, lag(stop_id), NA))
edges <- trip_edges %>% select(route, stop_id, prev_stop_id) %>% distinct()
# create stations dataframe with line, stop_id, stop_name
stations <- edges %>% left_join(station_data, by = c("stop_id"="stop_id")) %>% select(line=route, stop_id, stop_name)

```
## Express vs Local train Distribution

- Filter through all 1 and 2 train trips between station 96th - 14th (south bound only). 
- Calculate the time between two stations (trip time) for all trip across the day
- Compare the differences

```{r}

stops <- stations %>% filter(line == "1",
                                grepl(sprintf("%s$", "S"), stop_id)) %>%
     unique()

  
# find trip time during 96th station and 14th station
# local 1 train
local_train <- subway_data %>% 
  filter(stop_mta_id =="120S" | stop_mta_id == "132S",
         route_mta_id == "1" ) %>%
  left_join(stops, by = c("stop_mta_id" = "stop_id")) %>%
  group_by(realtime_trip_id) %>% 
  arrange (desc(departure_time)) %>%
  mutate(diff= round(first(departure_time)-last(departure_time))/60)

plot_local <- local_train %>% ggplot(aes(x=diff))+ geom_histogram()
plot_local
# express 2 train
express_train <- subway_data %>% 
  filter(stop_mta_id =="120S" | stop_mta_id == "132S",
         route_mta_id == "2" ) %>%
  left_join(stops, by = c("stop_mta_id" = "stop_id")) %>%
  group_by(realtime_trip_id) %>% 
  arrange (desc(departure_time)) %>%
  mutate(diff= round(first(departure_time)-last(departure_time))/60)

plot_express <- express_train  %>% ggplot(aes(x=diff))+ geom_histogram()
plot_express

```