---
title: "MTA First Map"
author: "Sasha Paulovich"
date: "July 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*with Ayliana, Brian, & Taxi*  

#### Load libraries
```{r libs, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggmap)
library(leaflet)
```


#### Load MTA data & Google Transit static files
```{r, warning=FALSE}
stations <- read_csv('http://web.mta.info/developers/data/nyct/subway/Stations.csv')
stops <- read_csv('../../data/google_transit_subway_static/stops.txt')
routes <- read_csv('../../data/google_transit_subway_static/routes.txt')
trips <- read_csv('../../data/google_transit_subway_static/trips.txt')
stop_times <- read_csv('../../data/google_transit_subway_static/stop_times.txt')
```


#### The `stations` data looks like:
```{r stations}
as.data.frame(stations) %>% head
```


#### We might want to view each route on its own line
```{r warning=FALSE}
new_stations <- stations %>% 
  select(complex_id = `Complex ID`, stop_id = `GTFS Stop ID`, stop_name = `Stop Name`, 
         stop_lat = `GTFS Latitude`, stop_lon = `GTFS Longitude`, line=Line, daytime_routes=`Daytime Routes`)

new_stations <- new_stations %>% 
  separate(daytime_routes, into=c('route1', 'route2', 'route3', 'route4'), sep=" ") 

ss1 <- new_stations %>% select(complex_id, stop_id, stop_name, stop_lat, stop_lon, line, route=route1)
ss2 <- new_stations %>% select(complex_id, stop_id, stop_name, stop_lat, stop_lon, line, route=route2)
ss3 <- new_stations %>% select(complex_id, stop_id, stop_name, stop_lat, stop_lon, line, route=route3)
ss4 <- new_stations %>% select(complex_id, stop_id, stop_name, stop_lat, stop_lon, line, route=route4)

routes_by_lines <- rbind(ss1, ss2, ss3, ss4) %>% filter(!is.na(route))

as.data.frame(routes_by_lines) %>% head
```


#### Use `stop_times` to understand the schedules/sequences of each line
```{r}
connections <- stop_times %>%
  left_join(stops) %>% 
  extract(trip_id, c("route_id"), regex=".*_.*_(.*)\\.\\..*", remove=FALSE) %>%
  mutate(stop_id = substr(stop_id, 1, 3),
    prev_stop_id = ifelse(trip_id == lag(trip_id), lag(stop_id), NA),
    prev_stop_lat = ifelse(trip_id == lag(trip_id), lag(stop_lat), NA),
    prev_stop_lon = ifelse(trip_id == lag(trip_id), lag(stop_lon), NA),
    prev_stop_name = ifelse(trip_id == lag(trip_id), lag(stop_name), NA))

sequences <- connections %>%
  left_join(routes) 

# catch NA color values
sequences$route_color <- replace_na(sequences$route_color, "000000") 

sequences <- sequences %>%
  mutate(route_color = sprintf("#%s", route_color)) %>%
  select(route_id, stop_id, stop_name, stop_lat, stop_lon, 
         prev_stop_id, prev_stop_name, prev_stop_lat, prev_stop_lon,
         route_color) %>%
  distinct 

```


#### Make a subway map!
```{r ggmap}

nyc_map <- get_map(location = c(lon = -73.9568247, lat = 40.7202688), maptype = "terrain", zoom = 12)
ggmap(nyc_map) +
 geom_point(data = sequences, aes(x = stop_lon, y = stop_lat)) +
 geom_segment(data = sequences, aes(x=prev_stop_lon, y=prev_stop_lat, xend=stop_lon, yend=stop_lat, color = route_id))

```


#### Make another (prettier) map
```{r leaflet}
map <- leaflet() %>%
  addTiles() %>%
  setView(-74.00, 40.71, zoom = 12) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircleMarkers(sequences$stop_lon, sequences$stop_lat, color = sequences$route_color,
                   popup = sequences$stop_name,
                   radius = 3) 

for (i in 1:nrow(sequences)) {
  map <- map %>%
    addPolylines(lat = c(sequences[i,]$stop_lat, sequences[i,]$prev_stop_lat),
                 lng = c(sequences[i,]$stop_lon, sequences[i,]$prev_stop_lon),
                 color = sequences[i,]$route_color,
                 weight = 1)
}

map
```
```

