---
title: "20180727_airtrain_map"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(igraph)
library(leaflet.extras)
library(RColorBrewer)
library(sp)
library(maptools)
library(broom)
library(httr)
library(rgdal)
library(mapview)
library(KernSmooth)
library(ggplot2)
library(gstat)
library(raster)
library(tidyverse)
```

```{r load data}
stops <- read_csv('../../data/google_transit_subway_static/stops.txt')
stops <- stops %>% dplyr::select(stop_id, stop_lat, stop_lon, stop_name)
routes_data <- read_csv('../../data/google_transit_subway_static/routes.txt')
source('../../src/path_finding.R')

load('../../data/at_igraph_edges.rdata')
igraph_edges <- mutate(at_igraph_edges, weight = `90%`)
igraph_edges$weight <- as.numeric(igraph_edges$weight)
mta_igraph <- graph_from_data_frame(igraph_edges)
```

```{r}
to <- "LGA"
vertices <- names(V(mta_igraph))
vertices <- vertices[vertices != to]
station_list <- list()
trip_time <- list()
for(i in 1:length(vertices)){
  path <- get_itinerary(mta_igraph, vertices[i], to, 1, stops = stops)
  station_list[i] <- vertices[i]
  path$weight <- as.numeric(path$weight)
  trip_time[i] <- sum(path$weight, na.rm = TRUE)
}

map_data <- data.frame(station = unlist(station_list))
map_data$trip_time <- unlist(trip_time)
map_data <- map_data %>% left_join(stops, by = c("station" = "stop_id")) %>%
  filter(! is.na(stop_lat)) %>% filter(trip_time != 0)
```

#### distance function
```{r}
distance <- function(graph, path) sum(E(graph, path=path)$weight)
```

#### geodistance (in km)
```{r}
Distance <- function(LatA, LonA, LatB, LonB){
  scaling_factor <- 110.25
  x <- LatA - LatB
  y <- (LonA - LonB) * cos(40.75 * (pi)/180)

  return (scaling_factor*sqrt(x * x + y * y))

}
```

#### Create a grid of points
```{r make-grid}
map_data_lats <- seq(min(map_data$stop_lat), max(map_data$stop_lat), by=0.002)
map_data_lons <- seq(min(map_data$stop_lon), max(map_data$stop_lon), by=0.002)
grid <- expand.grid(map_data_lats, map_data_lons) %>%
 dplyr::select(lat = Var1, lon = Var2)
```

#### Get subway travel time, walking time, total time
##### Filter for points reachable within 20 mins of walking
```{r get-times}
trip_time = vector()
station = vector()
walking_time = vector()
total_time = vector()
for(i in 1:nrow(grid)){
 result<- map_data %>% mutate(walking_time = 720*Distance(grid$lat[i], grid$lon[i], stop_lat, stop_lon), total_time = (walking_time + trip_time)%/%60)
 idx <- which.min(result$total_time)
 
 
 trip_time[i] <- result[idx, "trip_time"]
 station[i] <- result[idx, "stop_name"]
 walking_time[i] <- result[idx, "walking_time"]
 total_time[i] <- result[idx, "total_time"]
}
grid$trip_time <- trip_time
grid$nearest_stop <- station
grid$walking_time <- walking_time
grid$total_time <- total_time
grid <- grid %>% mutate(walking_mins = (walking_time %/% 60))
grid$log_mins <- log(grid$total_time)

filtered_grid <- grid %>% 
  filter(walking_mins <= 20)
```

#### Limit grid to points within NYC
```{r spatial-join}

r <- GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
nyc_neighborhoods <- readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)

filtered_grid <- grid %>%
  filter(! is.na(total_time)) %>%
  filter(walking_mins <= 20)

filtered_grid_spdf <- filtered_grid
coordinates(filtered_grid_spdf) <- ~lon + lat
proj4string(filtered_grid_spdf) <- proj4string(nyc_neighborhoods)
matches <- over(filtered_grid_spdf, nyc_neighborhoods)
filtered_grid <- cbind(filtered_grid, matches)
filtered_grid <- filtered_grid %>%
  filter(!is.na(neighborhood))
coords <- filtered_grid[c("lon", "lat")]

gridded(filtered_grid_spdf) <- TRUE
```


### **Heatmap with raster layer**
```{r}
#Interpolate surface and fix the output
idw <- idw(formula=total_time ~ 1, locations=filtered_grid_spdf, newdata = filtered_grid_spdf)  # apply idw model for the data

residual_grid <- raster(idw, "var1.pred")
contourr <- rasterToContour(residual_grid)


rr <- mask(residual_grid, nyc_neighborhoods)
crs(rr) <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

clrs <- brewer.pal(11, "RdYlGn")

grid_pal <- colorNumeric(
  palette = clrs,
  domain = filtered_grid$total_time,
  reverse = TRUE,
  na.color = "transparent")

m <- leaflet(nyc_neighborhoods) %>% 
  addTiles() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  setView(-73.98, 40.75, zoom = 14) %>%
  addLegend("bottomright", pal = grid_pal, values = filtered_grid$total_time,
    title = paste("Commute time to ", to),
    labFormat = labelFormat(suffix = " min"),
    opacity = 1)
  
  addRasterImage(m, rr, color=grid_pal, opacity = 0.4)
```

