---
title: "20180726_mta_triptime_distribution"
author: "Phoebe Nguyen, Akbar Mirza"
date: "July 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(ggthemes)
library(ROCR)

load(file = "../../data/todd_subway_realtime.RData")
source(file = "../../src/itinerary_evaluation.R")
```

### Multi-leg trip itinerary evaluation

Evaluating Trip Itineraries With Multiple Legs.

#### Function Definition

```{r Data Input 1}
# TEST DATA for itinerary

test_data_1 <- read_csv('../../data/itineraries-Red-Line-96-23-train.csv')

# filter out event and adding direction to station id
test_train_1 <- test_data_1 %>%
  filter(event != "travel", itinerary_id < 4)

#output for first data input
all_itin_df.1 <- compute_all_itins(test_train_1)%>%
  mutate(group='red')

```

```{r Data Input 2}
# TEST DATA for itinerary
test_data_2 <- read_csv('../../data/itineraries-Orange-Line-96-23-train.csv')


# filter out event and adding direction to station id
test_train_2 <- test_data_2 %>%
  filter(event != "travel", itinerary_id < 4)

#output for first data input
all_itin_df.2 <- compute_all_itins(test_train_2) %>%
  mutate(group='orange')

#combine first line df with second line df
all_itin_df <- bind_rows(all_itin_df.1, all_itin_df.2)

###### 
#Overall Evaluation

plot_data <- all_itin_df %>% 
  mutate(day_of_week = weekdays(leg1_start_time), hour = hour(leg1_start_time)) %>%
  filter(isWeekend(day_of_week) == F, hour >= 7 & hour < 10) %>%
  group_by(group,itin_id) %>%
  mutate(avg= mean(time_diff), stdv= sd(time_diff))

plot_data %>% select(itin_id, avg, stdv, group) %>% distinct()

```
```{r density evaluation}

top_2_trips <- all_itin_df %>% group_by(group) %>% filter(itin_id == "1")
  
plot_densities(top_2_trips)

###
```

```{r test time taken}
# NOTE: DEBUG CODE
# start.time <- Sys.time()
# new_test_df <- get_itinerary_times(test_itin)
# end.time <- Sys.time()
# time.taken <- end.time - start.time
# time.taken

# save(test_df, file = "test_df_with_orig_method.RData")

# start.time <- Sys.time()
# test_leg_data <- get_leg_data("A", "A27S", "A31S")
# end.time <- Sys.time()
# time.taken <- end.time - start.time
# time.taken
```

#### Plots for Debugging

```{r debugging_plots}

# TODO: Write A Function To Show Trains On Plot

# NOTE: DEBUG PLOT - show all trains individually on plot

# filtered_test_df <- test_df %>% filter(hour(leg1_start_time) >= 8 & hour(leg1_start_time) <= 9)

# plot_data <- bind_rows(train_data[[1]], train_data[[2]], train_data[[3]])
# plot_data %>% filter(month(start_time) == 2 & day(start_time) == 16 & hour(start_time) > 19 & hour(start_time) < 24) %>%
#   arrange(start_time) %>%
#   mutate(itin = row_number()) %>%
#   ggplot(aes(color = route_mta_id)) +
#   geom_segment(aes(x = start_time, xend = departure_time, y = itin, yend = itin)) +
#   geom_text(aes(label = realtime_trip_id, x = start_time, y = itin))

# TODO: Write A Function To Show Itineraries On Plot

# ITINERARY PLOT
# filtered_test_df %>% mutate(itin = row_number()) %>%
#   filter(itin <= 5) %>%
#   ggplot() +
#     geom_segment(aes(x = leg1_start_time, xend = leg1_end_time, y = itin, yend = itin), color = 'red') +
#     geom_segment(aes(x = leg2_start_time, xend = leg2_end_time, y = itin, yend = itin), color = 'blue') +
#     geom_segment(aes(x = leg3_start_time, xend = leg3_end_time, y = itin, yend = itin), color = 'green') +
#     geom_text(aes(label = leg1_trip_id, x = leg1_start_time, y = itin), color = "red") +
#     geom_text(aes(label = leg2_trip_id, x = leg2_start_time, y = itin), color = "blue") +
#     geom_text(aes(label = leg3_trip_id, x = leg3_start_time, y = itin), color = "green") +
#     ylim(c(0, 10))

# filtered_test_df %>% ggplot() +
#   geom_histogram(aes(x = time_diff))
```

#### Frontier Plots

```{r frontier-plot}
# given a df with historical time_diffs for many initineraries
# will return a plot that maps avg time_diff vs variance

plot_frontier <- function(plot_data) {

  # plot_data <- itins_df %>%
  #   mutate(day_of_week = weekdays(leg1_start_time), hour = hour(leg1_start_time)) %>%
  #   # filter out weekends, and only get hour_start, hour_end
  #   filter(isWeekend(day_of_week) == F, hour >= 7 & hour < 10) %>%
  #   group_by(itin_id) %>%
  #   mutate(avg = mean(time_diff), stdv = sd(time_diff))

  plot <- plot_data %>% ggplot(aes(x = stdv, y = avg)) +
    geom_point() +
    xlab('Standard Deviation of Trip Time') +
    ylab('Average Trip Time') +
    geom_text(aes(label = paste0(group, itin_id,sep='')), hjust = 0.5, vjust = 2)+
    ylim(c(10, 30))

  return(plot)
}

plot_frontier(plot_data)
```

#### AUC Plots

```{r AUC}
# pull out the number from the ROCR package with pred <- predictions(predicted, actual); performance(pred, 'auc')@y.values[[1]]
# or  with the pROC package: as.numeric(auc(response = actual, predictor = predicted))
# itinerary is the actual value, trip time is the predicted value

# Choosing pairs of itinerary for comparison
#first_itin <- '1'
#sec_itin <- '3'
# auc_df <- all_itin_df.1%>%
#   filter(itin_id == first_itin | itin_id == sec_itin) %>%
#   select(itin_id, time_diff)

auc_df <- top_2_trips %>% mutate(itin_line = as.factor(paste0(group,itin_id, sep=''))) %>% ungroup() %>% select(itin_line, time_diff)
  
auc_function <- function(auc_df) {
pred <- prediction(as.numeric(auc_df$time_diff, units = "mins"), as.factor(auc_df$itin_line))
perf_nb <- performance(pred, 'auc')@y.values[[1]]
perf <- performance(pred, 'auc')
ifelse( perf_nb < 0.5, return(1 - perf_nb), return(perf))
}

auc_function(auc_df)


```
## Interesting Examples

#### Midtown to Jamaica

```{r midtown-jamaica-plots}

# load midtown-jamaica data, and clean for our uses
#   - filter out event and add direction to station id
mj_data <- read_csv('../../data/itineraries-Midtown-Jamaica.csv') %>%
  filter(event != "travel", itinerary_id < 2)

all_itin_df <- compute_all_itins(mj_data, subway_data)

all_itin_df_clean <- all_itin_df %>% filter(time_diff > 0)

plot_densities(all_itin_df_clean)

```

#### Atlantic to Fulton (Morning)

```{r atlantic-fulton-plots}

# load midtown-jamaica data, and clean for our uses
#   - filter out event and add direction to station id
# compare 2-3 train with the 5 train

mj_data <- read_csv('../../data/itineraries-Midtown-Jamaica.csv') %>%
  filter(event != "travel", itinerary_id < 4)



# TODO: UNCOMMENT WHEN ALL SPECIAL CASES RESOLVED
itin_max <- max(mj_data$itinerary_id)
result <- vector ("list", length = itin_max)

for (i in 1:itin_max) {
  itin <- mj_data %>% filter(itinerary_id == i)
  result[[i]] <- get_itinerary_times(itin, subway_data) %>% mutate(itin_id=sprintf("%s: %s", i, label))
}

all_itin_df <- bind_rows(result)

# TODO: Refactor This into plot_densities function
filtered <- all_itin_df %>%
  mutate(day_of_week = weekdays(leg1_start_time),
         hour = hour(leg1_start_time)) %>%
  filter(isWeekend(day_of_week) == F,
         hour >= 7 & hour < 10)
filtered$itin_id <- as.factor(filtered$itin_id)

filtered %>%
  ggplot(aes(x = time_diff, group=itin_id, col=itin_id, fill=itin_id)) +
  geom_density(alpha = 0.5) +
  scale_fill_discrete(guide = guide_legend()) +
  theme(legend.position = "bottom", legend.direction = "vertical", legend.key.size = unit(1.5, 'lines'))
  # geom_histogram(), position = "identity", alpha = 0.5)

```
