---
title: "L train"
author: "Sasha, Ayliana, Taxi"
date: "July 26, 2018"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#### Load libraries
```{r warning=FALSE, message=FALSE}
library(igraph)
library(leaflet)
library(RColorBrewer)
library(geosphere)
library(sp)
library(maptools)
library(broom)
library(httr)
library(rgdal)
library(ggmap)
library(KernSmooth)
library(ggplot2)
library(gstat)
library(raster)
library(tidyverse)
```

#### Load data
```{r load data}
load('../../data/reverse_mta_igraph_rush_hour.RData')
stops <- read_csv('../../data/google_transit_subway_static/stops.txt')
stops <- stops %>% select(stop_id, stop_lat, stop_lon, stop_name)
source('../../src/path_finding.R')
```

#### distance function
```{r}
distance <- function(graph, path) sum(E(graph, path=path)$weight)
```

#### geodistance (in km)
```{r}
Distance <- function(LatA, LonA, LatB, LonB){
  scaling_factor <- 110.25
  x <- LatA - LatB
  y <- (LonA - LonB) * cos(40.75 * (pi)/180)

  return (scaling_factor*sqrt(x * x + y * y))

}
```

#### Find shortest paths from 96 St
```{r regular}
map_data <- get.all.shortest.paths(mta_igraph, "120", mode = "out")

map_data <- map_data$res %>% lapply(function(x)data.frame(stop_id = names(x)[length(x)], distance <- distance(mta_igraph, x), path = paste0(names(x), collapse = '>'))) %>%
  reduce(rbind) 
map_data <- map_data %>% left_join(stops)
names(map_data) <- c("stop_id", "distance", "path", "stop_lat", "stop_lon", "stop_name")
map_data <- map_data %>%
  mutate(mins = distance%/%60,
         log_mins = log(mins),
         min_interval = cut(mins, seq(0, max(mins), by = 5), include.lowest = TRUE))
```

#### Create a grid of points
```{r make-grid}
map_data_lats <- seq(min(map_data$stop_lat), max(map_data$stop_lat), by=0.002)
map_data_lons <- seq(min(map_data$stop_lon), max(map_data$stop_lon), by=0.002)
grid <- expand.grid(map_data_lats, map_data_lons) %>%
 select(lat = Var1, lon = Var2)
```

#### Get subway travel time, walking time, total time
##### Filter for points reachable within 20 mins of walking
```{r get-times}
total_time = vector()
walking = vector()
station = vector()
for(i in 1:nrow(grid)){
 result<- map_data %>% mutate(walking_time = 720*Distance(grid$lat[i], grid$lon[i], stop_lat, stop_lon), 
                              total_time = (walking_time + distance))
 idx <- which.min(result$total_time)

 total_time[i] <- result[idx, "total_time"]
 walking[i] <- result[idx, "walking_time"]
 station[i] <- result[idx, "stop_name"]
 # print(walking[i])
}
grid$time <- total_time
grid$walking <- walking
grid$nearest_stop <- station
grid <- grid %>% mutate(total_time_mins = time%/%60, walking_mins = walking%/%60, subway_mins = total_time_mins - walking_mins)
grid$log_mins <- log(grid$total_time_mins)

filtered_grid <- grid %>%
  filter(walking_mins <= 20) %>%
  mutate(min_interval = cut(total_time_mins, seq(0, max(total_time_mins), by = 5), include.lowest = TRUE),
         bin = cut(total_time_mins, seq(0, max(total_time_mins), by = 5), include.lowest = TRUE, labels = FALSE))
```


#### Set color palette
```{r colors}

clrs <- brewer.pal(25, "RdYlGn")

# pal <- colorNumeric(
#   palette = clrs,
#   domain = filtered_grid$time,
#   reverse = TRUE)

pal <- colorNumeric(
  palette = clrs,
  domain = filtered_grid$bin,
  reverse = TRUE)

```


#### Map grid of points and stations
```{r with-stations}

leaflet() %>%
  addTiles() %>%
  setView(-74.00, 40.71, zoom = 12) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircleMarkers(data = filtered_grid, lng = ~lon, lat = ~lat,
                   color = ~pal(bin), 
                   popup = paste(round(filtered_grid$total_time_mins, 2), "mins", "<br/>", filtered_grid$nearest_stop), 
                   radius = 20, stroke = FALSE, fillOpacity = 0.1) %>%
addCircleMarkers(data = map_data, lng = ~stop_lon, lat = ~stop_lat,
                   popup = paste("<b>", map_data$stop_name, map_data$stop_id, "</b>",
                                 "<br/>", round(map_data$distance/60, 2), "mins"),
                   radius = 4,
                   color = "blue",
                   fillOpacity = 0.3)
```


#### Limit grid to points within NYC
```{r spatial-join}

# nyc_map <- get_map(location = c(lon = -74.00, lat = 40.71), maptype = "terrain", zoom = 11)

r <- GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
nyc_neighborhoods <- readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)


filtered_grid_spdf <- filtered_grid
coordinates(filtered_grid_spdf) <- ~lon + lat
proj4string(filtered_grid_spdf) <- proj4string(nyc_neighborhoods)
matches <- over(filtered_grid_spdf, nyc_neighborhoods)
filtered_grid <- cbind(filtered_grid, matches)
filtered_grid <- filtered_grid %>%
  filter(!is.na(neighborhood))

leaflet(nyc_neighborhoods) %>%
  addTiles() %>% 
  addProviderTiles("CartoDB.Positron") %>%
  setView(-73.98, 40.75, zoom = 12) %>%
  addCircleMarkers(data = filtered_grid, lng = ~lon, lat = ~lat,
                   color = ~pal(bin), 
                   popup = paste("walking:", filtered_grid$walking_mins, "mins", "<br/>",
                                 "subway:", filtered_grid$subway_mins, "mins", "<br/>",
                                 "total:", filtered_grid$total_time_mins, "mins", "<br/>",
                                 "interval:", filtered_grid$min_interval, "mins", "<br/>",
                                 filtered_grid$nearest_stop), 
                   radius = 10, stroke = FALSE, fillOpacity = 0.6)

```


### **Heatmap with raster layer**
```{r}


r <- GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
nyc_neighborhoods <- readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)


filtered_grid <- grid %>%
  filter(walking_mins <= 20) %>%
  mutate(min_interval = cut(total_time_mins, seq(0, max(total_time_mins), by = 5), include.lowest = TRUE),
         bin = cut(total_time_mins, seq(0, max(total_time_mins), by = 5), include.lowest = TRUE, labels = FALSE))

filtered_grid_spdf <- filtered_grid
coordinates(filtered_grid_spdf) <- ~lon + lat
proj4string(filtered_grid_spdf) <- proj4string(nyc_neighborhoods)
matches <- over(filtered_grid_spdf, nyc_neighborhoods)
filtered_grid <- cbind(filtered_grid, matches)
filtered_grid <- filtered_grid %>%
  filter(!is.na(neighborhood))

coords <- filtered_grid[c("lon", "lat")]

gridded(filtered_grid_spdf) <- TRUE



plot(filtered_grid_spdf, cex = 0.2, col = "grey")

points(coords, pch =1, col = "black", cex = 0.1)
#Interpolate surface and fix the output
idw <- idw(formula=sqrt(total_time_mins) ~ 1, locations=filtered_grid_spdf, newdata = filtered_grid_spdf)  # apply idw model for the data

residual_grid <- raster(idw, "var1.pred")
contourr <- rasterToContour(residual_grid)


rr <- mask(residual_grid, nyc_neighborhoods)
crs(rr) <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

clrs <- brewer.pal(length(contourr@lines), "RdYlGn")

# lines_pal <- colorNumeric(
#   palette = clrs,
#   domain = seq(1:length(contourr$lines)),
#   reverse = TRUE,
#   na.color = "transparent")

grid_pal <- colorNumeric(
  palette = clrs,
  domain = sqrt(filtered_grid$total_time_mins),
  reverse = TRUE,
  na.color = "transparent")




m <- leaflet(nyc_neighborhoods) %>% 
  addTiles() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  setView(-73.98, 40.75, zoom = 14) %>%
  # addPolylines(data = contourr, fillOpacity = 2, fillColor = rev(clrs),
  #              color = rev(clrs), opacity=10, weight=1) %>%
  # addCircleMarkers(data = filtered_grid, lng = ~lon, lat = ~lat, color = "transparent", radius = 15,
  #                  popup = paste("walking:", filtered_grid$walking_mins, "mins", "<br/>",
  #                                "subway:", filtered_grid$subway_mins, "mins", "<br/>",
  #                                "total:", filtered_grid$total_time_mins, "mins", "<br/>",
  #                                "interval:", filtered_grid$min_interval, "mins", "<br/>",
  #                                filtered_grid$nearest_stop)) %>%
  addCircleMarkers(data = map_data, lng = ~stop_lon, lat = ~stop_lat,
                   color = ~grid_pal(sqrt(mins)),
                   popup = paste("<b>", map_data$stop_name, "</b>", "<br/>",
                                 "subway:", map_data$mins, "mins", "<br/>"),
                   radius = 4, stroke = FALSE, fillOpacity =0.9) %>%
  addLegend("bottomright", pal = grid_pal, values = sqrt(map_data$mins),
    title = "Commute time to 96 St",
    labFormat = labelFormat(suffix = " mins", transform = function(x) x * x),
    opacity = 1)

  
m
  
  addRasterImage(m, rr, color=grid_pal, opacity = 0.4)
  
# ggplot(filtered_grid) +
#   geom_histogram(aes(x = log(total_time_mins)))
# 
# quantile(filtered_grid$total_time_mins, seq(0,1,.01))

```


