---
title: "20180726_reliability_tax"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(igraph)
library(leaflet.extras)
library(RColorBrewer)
library(data.table)
library(sp)
library(maptools)
library(broom)
library(httr)
library(rgdal)
library(mapview)
library(KernSmooth)
library(ggplot2)
library(gstat)
library(raster)
```

```{r load data}
stops <- read_csv('../../data/google_transit_subway_static/stops.txt')
stops <- stops %>% select(stop_id, stop_lat, stop_lon, stop_name)
routes_data <- read_csv('../../data/google_transit_subway_static/routes.txt')
source('../../src/path_finding.R')

load('../../data/igraph_edges.rdata')
igraph_edges <- mutate(igraph_edges, weight = `50%`)
igraph_edges <- igraph_edges %>% select(stop_id, nxt_stop_id, weight, route_id, `90%`)
igraph_edges$weight <- as.numeric(igraph_edges$weight)
igraph_edges$`90%` <- as.numeric(igraph_edges$`90%`)
mta_igraph <- graph_from_data_frame(igraph_edges)
igraph_edges <- igraph_edges %>% select(stop_id) %>% mutate(vertex_id = substr(stop_id, 1, 3)) %>% filter(vertex_id != "H01" & vertex_id != "R20" & vertex_id != "R18" & vertex_id != "S09")
vertices <- igraph_edges$vertex_id[1:470]
vertices <- vertices %>% unique()
```

```{r}
from <- "R19"
#vertices <- names(V(mta_igraph))
vertices <- vertices[vertices != from]
station_list <- list()
time_50 <- list()
time_90 <- list()
for(i in 1:length(vertices)){
    print(vertices[i])
  path <- get_itinerary(mta_igraph, from , vertices[i], 1, stops = stops, attributeNames = '90%')
  station_list[i] <- vertices[i]
  path$weight <- as.numeric(path$weight)
  time_50[i] <- sum(path$weight, na.rm = TRUE)
  path$`90%` <- as.numeric(path$`90%`)
  time_90[i] <- sum(path$`90%`, na.rm = TRUE)
}

map_data <- data.frame(station = unlist(station_list))
map_data$time_50 <- unlist(time_50)
map_data$time_90 <- unlist(time_90)
map_data <- map_data %>% left_join(stops, by = c("station" = "stop_id")) %>%
  filter(! is.na(stop_lat))
```

#### distance function
```{r}
distance <- function(graph, path) sum(E(graph, path=path)$weight)
```

#### geodistance (in km)
```{r}
Distance <- function(LatA, LonA, LatB, LonB){
  scaling_factor <- 110.25
  x <- LatA - LatB
  y <- (LonA - LonB) * cos(40.75 * (pi)/180)

  return (scaling_factor*sqrt(x * x + y * y))

}
```

#### Create a grid of points
```{r make-grid}
map_data_lats <- seq(min(map_data$stop_lat), max(map_data$stop_lat), by=0.002)
map_data_lons <- seq(min(map_data$stop_lon), max(map_data$stop_lon), by=0.002)
grid <- expand.grid(map_data_lats, map_data_lons) %>%
 select(lat = Var1, lon = Var2)
```

#### Get subway travel time, walking time, total time
##### Filter for points reachable within 20 mins of walking
```{r get-times}
time_50 = vector()
time_90 = vector()
station = vector()
walking_time = vector()
for(i in 1:nrow(grid)){
 result<- map_data %>% mutate(walking_time = 720*Distance(grid$lat[i], grid$lon[i], stop_lat, stop_lon), total_time = (walking_time + time_50))
 idx <- which.min(result$total_time)
 
 
 time_50[i] <- result[idx, "time_50"]
 time_90[i] <- result[idx, "time_90"]
 station[i] <- result[idx, "stop_name"]
 walking_time[i] <- result[idx, "walking_time"]
}
grid$time_50P <- time_50
grid$time_90P<- time_90
grid$nearest_stop <- station
grid$walking_time <- walking_time
grid <- grid %>% mutate(time_diff = round((time_90P-time_50P)/time_50P*100), walking_mins = (walking_time %/% 60))
grid$log_mins <- log(grid$time_diff)

filtered_grid <- grid %>%
  filter(walking_mins <= 20) %>%
  mutate(min_interval = cut(time_diff, seq(0, max(time_diff), by = 5), include.lowest = TRUE),
         bin = cut(time_diff, seq(0, max(time_diff), by = 5), include.lowest = TRUE, labels = FALSE))
```


#### Set color palette
```{r colors}

clrs <- brewer.pal(25, "RdYlGn")

# pal <- colorNumeric(
#   palette = clrs,
#   domain = filtered_grid$time,
#   reverse = TRUE)

pal <- colorNumeric(
  palette = clrs,
  domain = filtered_grid$bin,
  reverse = TRUE)

```


#### Map grid of points and stations
```{r with-stations}

leaflet() %>%
  addTiles() %>%
  setView(-74.00, 40.71, zoom = 12) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircleMarkers(data = filtered_grid, lng = ~lon, lat = ~lat,
                   color = ~pal(bin), 
                   popup = paste(round(filtered_grid$time_diff, 2), "mins", "<br/>", filtered_grid$nearest_stop), 
                   radius = 20, stroke = FALSE, fillOpacity = 0.1) %>%
addCircleMarkers(data = map_data, lng = ~stop_lon, lat = ~stop_lat,
                   popup = paste("<b>", map_data$stop_name, map_data$stop_id, "</b>",
                                 "<br/>", round(map_data$distance/60, 2), "mins"),
                   radius = 4,
                   color = "blue",
                   fillOpacity = 0.3)
```


#### Limit grid to points within NYC
```{r spatial-join}

# nyc_map <- get_map(location = c(lon = -74.00, lat = 40.71), maptype = "terrain", zoom = 11)

r <- GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
nyc_neighborhoods <- readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)


filtered_grid_spdf <- filtered_grid
coordinates(filtered_grid_spdf) <- ~lon + lat
proj4string(filtered_grid_spdf) <- proj4string(nyc_neighborhoods)
matches <- over(filtered_grid_spdf, nyc_neighborhoods)
filtered_grid <- cbind(filtered_grid, matches)
filtered_grid <- filtered_grid %>%
  filter(!is.na(neighborhood))

leaflet(nyc_neighborhoods) %>%
  addTiles() %>% 
  addProviderTiles("CartoDB.Positron") %>%
  setView(-73.98, 40.75, zoom = 12) %>%
  addCircleMarkers(data = filtered_grid, lng = ~lon, lat = ~lat,
                   color = ~pal(bin), 
                   popup = paste("time_diff:", filtered_grid$time_diff, "%", "<br/>",
                                 filtered_grid$nearest_stop), 
                   radius = 10, stroke = FALSE, fillOpacity = 0.6)

```


### **Heatmap with raster layer**
```{r}

filtered_grid <- grid %>%
  filter(walking_mins <= 20) %>%
  mutate(min_interval = cut(time_diff, seq(0, max(time_diff), by = 5), include.lowest = TRUE),
         bin = cut(time_diff, seq(0, max(time_diff), by = 5), include.lowest = TRUE, labels = FALSE))

filtered_grid_spdf <- filtered_grid
coordinates(filtered_grid_spdf) <- ~lon + lat
proj4string(filtered_grid_spdf) <- proj4string(nyc_neighborhoods)
matches <- over(filtered_grid_spdf, nyc_neighborhoods)
filtered_grid <- cbind(filtered_grid, matches)
filtered_grid <- filtered_grid %>%
  filter(!is.na(neighborhood))
coords <- filtered_grid[c("lon", "lat")]

gridded(filtered_grid_spdf) <- TRUE



plot(filtered_grid_spdf, cex = 0.2, col = "grey")

points(coords, pch =1, col = "black", cex = 0.1)
#Interpolate surface and fix the output
idw <- idw(formula=sqrt(diff_time) ~ 1, locations=filtered_grid_spdf, newdata = filtered_grid_spdf)  # apply idw model for the data

residual_grid <- raster(idw, "var1.pred")
contourr <- rasterToContour(residual_grid)


rr <- mask(residual_grid, nyc_neighborhoods)
crs(rr) <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

clrs <- brewer.pal(length(contourr@lines), "RdYlGn")

# lines_pal <- colorNumeric(
#   palette = clrs,
#   domain = seq(1:length(contourr$lines)),
#   reverse = TRUE,
#   na.color = "transparent")

grid_pal <- colorNumeric(
  palette = clrs,
  domain = sqrt(filtered_grid$total_time_mins),
  reverse = TRUE,
  na.color = "transparent")




m <- leaflet(nyc_neighborhoods) %>% 
  addTiles() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  setView(-73.98, 40.75, zoom = 14) %>%
  # addPolylines(data = contourr, fillOpacity = 2, fillColor = rev(clrs),
  #              color = rev(clrs), opacity=10, weight=1) %>%
  # addCircleMarkers(data = filtered_grid, lng = ~lon, lat = ~lat, color = "transparent", radius = 15,
  #                  popup = paste("walking:", filtered_grid$walking_mins, "mins", "<br/>",
  #                                "subway:", filtered_grid$subway_mins, "mins", "<br/>",
  #                                "total:", filtered_grid$total_time_mins, "mins", "<br/>",
  #                                "interval:", filtered_grid$min_interval, "mins", "<br/>",
  #                                filtered_grid$nearest_stop)) %>%
  addCircleMarkers(data = map_data, lng = ~stop_lon, lat = ~stop_lat,
                   color = ~grid_pal(sqrt(mins)),
                   popup = paste("<b>", map_data$stop_name, "</b>", "<br/>",
                                 "subway:", map_data$mins, "mins", "<br/>"),
                   radius = 4, stroke = FALSE, fillOpacity =0.9) %>%
  addLegend("bottomright", pal = grid_pal, values = sqrt(map_data$mins),
    title = "Commute time to 96 St",
    labFormat = labelFormat(suffix = " mins", transform = function(x) x * x),
    opacity = 1)

  
m
  
  addRasterImage(m, rr, color=grid_pal, opacity = 0.4)
```

