---
title: "20180723_mta_triptime_distribution"
author: "Phoebe Nguyen, Akbar Mirza"
date: "July 23, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(ggthemes)

# load todd's subway_data
# load(file = "../../data/todd_subway_realtime.RData")
# NOTE: How We Get Subway_data_2
# subway_data.2 <- subway_data %>%
#   group_by(realtime_trip_id) %>%
#   arrange(desc(departure_time)) %>%
#   mutate(arrival_time=lead(departure_time)) %>%
#   ungroup()
#
# save(subway_data.2, file = "../../data/todd_subway_realtime_2.RData")
load(file = "../../data/todd_subway_realtime_2.RData")

# load stop_times from GTFS Static
stop_times <- read_csv("../../data/google_transit_subway_static/stop_times.txt")

# load station_data from mta
station_data <- read_csv("http://web.mta.info/developers/data/nyct/subway/Stations.csv")

# get stop_id and stop_name fields, and create a stop_id with N and S appended
station_data <- station_data %>% group_by(`GTFS Stop ID`, `Stop Name`) %>%
  select(stop_id = `GTFS Stop ID`, stop_name = `Stop Name`) %>%
  mutate(stop_id_N = sprintf('%sN', stop_id), stop_id_S = sprintf('%sS', stop_id)) %>%
  gather(`stop_id_N`, `stop_id_S`, key = "stop_ids", value = "stop_id") %>%
  select(stop_name, stop_id)

################################################################################
# Getting Station Information
################################################################################
# Generate edges between stations
trips <- stop_times %>% extract(trip_id, "route", regex=".*_.*_(.*)\\.\\..*", remove = FALSE)
trip_edges <- trips %>% mutate(prev_stop_id = ifelse(lag(trip_id) == trip_id, lag(stop_id), NA))
edges <- trip_edges %>% select(route, stop_id, prev_stop_id) %>% distinct()
# create stations dataframe with line, stop_id, stop_name
stations <- edges %>% left_join(station_data, by = c("stop_id"="stop_id")) %>% select(line=route, stop_id, stop_name)
```

### Computing Local + Express Wait Times On Large Scale Efficiently

```{r example-for-trips}

compute_itenerary_pair <- function(start_lines, end_lines, start_id, transfer_start_id, transfer_end_id, end_id, start_time) {

  # TODO: filter subway_data to only trips within a certain time_interval

  # get train information for start_lines at start_id
  leg1_data <- subway_data.2 %>%
    filter(stop_mta_id == start_id | stop_mta_id == transfer_start_id,
           # TODO: modify filter to take multiple lines
           route_mta_id == start_lines) %>%
    group_by(realtime_trip_id) %>%
    mutate(trip_start_time = min(departure_time)) %>%
    # get rid of records for extra record at start stops
    filter(n() >= 2, stop_mta_id == transfer_start_id) %>%
    arrange(arrival_time)

  leg2_data <- subway_data.2 %>%
    filter(stop_mta_id == transfer_end_id | stop_mta_id == end_id,
            # TODO: modify filter to take multiple lines
            route_mta_id == end_lines) %>%
    group_by(realtime_trip_id) %>%
    mutate(trip_end_time = max(departure_time)) %>%
    # get rid of records for extra record at start stops
    filter(n() >= 2, stop_mta_id == transfer_end_id) %>%
    arrange(departure_time)


  leg1_ptr <- 1
  leg2_ptr <- 1
  # create vectors to store new info
  diffs <- vector('numeric')
  start_times <- vector('double')
  transfer_arrival_times <- vector('double')
  end_times <- vector('double')
  transfer_departure_times <- vector('double')
  realtime_start_ids <- vector('numeric')
  realtime_end_ids <- vector('numeric')

  while (leg1_ptr < nrow(leg1_data)) {

    if (leg2_data$departure_time[leg2_ptr] > leg1_data$arrival_time[leg1_ptr]) {
      # populate fields that will be used for our returned data_frame
      realtime_start_ids <- c(realtime_start_ids, leg1_data$realtime_trip_id[leg1_ptr])
      start_times <- c(start_times, leg1_data$trip_start_time[leg1_ptr])
      transfer_arrival_times <- c(transfer_arrival_times, leg1_data$arrival_time[leg1_ptr])
      realtime_end_ids <- c(realtime_end_ids, leg2_data$realtime_trip_id[leg2_ptr])
      transfer_departure_times <- c(transfer_departure_times, leg2_data$departure_time[leg2_ptr])
      end_times <- c(end_times, leg2_data$trip_end_time[leg2_ptr])
      diffs <- c(diffs,
                 as.numeric(difftime(leg2_data$trip_end_time[leg2_ptr],
                                     leg1_data$trip_start_time[leg1_ptr]),
                            units = "mins"))
      
      leg1_ptr = leg1_ptr + 1
    } else {
      leg2_ptr = leg2_ptr + 1
    }
  
  }

  new_df <- data.frame(start_trip_id = realtime_start_ids,
                       starts = as.POSIXct(start_times, origin = "1970-01-01", tz = "UTC"),
                       transfer_starts = as.POSIXct(transfer_arrival_times, origin = "1970-01-01", tz = "UTC"),
                       end_trip_id = realtime_end_ids,
                       transfer_ends = as.POSIXct(transfer_departure_times, origin = "1970-01-01", tz = "UTC"),
                       ends = as.POSIXct(end_times, origin = "1970-01-01", tz = "UTC"),
                       diffs = diffs)

  return(new_df)
}

local_line <- "1"
express_line <- "2"
start_stop_id <- "120S"
transfer_stop_id <- "127S"
end_stop_id <- "131S"
start_time <- "2018-01-20 09:30:00"

# Getting 2 Trains
data_2_train <- subway_data.2 %>%
  filter(stop_mta_id == "120S" | stop_mta_id == "127S",
         route_mta_id == "2") %>%
  # filter(ymd_hms(departure_time) > ymd_hms(start_time)) %>%
  group_by(realtime_trip_id) %>%
  mutate(start_time = min(departure_time)) %>%
  filter(n() >= 2, stop_mta_id == "127S") %>%
  arrange(arrival_time)

# Getting 1 Trains
data_1_train <- subway_data.2 %>%
  filter(stop_mta_id == "127S" | stop_mta_id == end_stop_id,
         route_mta_id == local_line) %>%
  # filter(ymd_hms(departure_time) > ymd_hms(start_time)) %>%
  group_by(realtime_trip_id) %>%
  mutate(end_time = max(departure_time)) %>%
  filter(n() >= 2, stop_mta_id == "127S") %>%
  arrange(departure_time)


# NOTE: train 1 start time and train 2 end time for debugging and evaluating purposes
i = 1
j = 1
times <- vector('numeric')
start_times <- vector('double')
transfer_arrival_times <- vector('double')
end_times <- vector('double')
transfer_departure_times <- vector('double')
realtime_start_ids <- vector('numeric')
realtime_end_ids <- vector('numeric')

while (i < nrow(data_2_train)) {
  if (data_1_train$departure_time[j] > data_2_train$arrival_time[i]) {
    # df <- data.frame(trip_time = 0, start_trip = 0, end_trip = 0)
    realtime_start_ids <- c(realtime_start_ids, data_2_train$realtime_trip_id[i])
    start_times <- c(start_times, data_2_train$start_time[i])
    transfer_arrival_times <- c(transfer_arrival_times, data_2_train$arrival_time[i])
    realtime_end_ids <- c(realtime_end_ids, data_1_train$realtime_trip_id[j])
    transfer_departure_times <- c(transfer_departure_times, data_1_train$departure_time[j])
    end_times <- c(end_times, data_1_train$end_time[j])
    times <- c(times, as.numeric(difftime(data_1_train$end_time[j], data_2_train$start_time[i]), units = "mins"))
    i = i + 1
  } else {
    j = j + 1
  }
}

# verify with real data
new_df <- data.frame(start_trip_id = realtime_start_ids,
                     starts = as.POSIXct(start_times, origin = "1970-01-01", tz = "UTC"),
                     transfer_starts = as.POSIXct(transfer_arrival_times, origin = "1970-01-01", tz = "UTC"),
                     end_trip_id = realtime_end_ids,
                     transfer_ends = as.POSIXct(transfer_departure_times, origin = "1970-01-01", tz = "UTC"),
                     ends = as.POSIXct(end_times, origin = "1970-01-01", tz = "UTC"),
                     diffs = times)

# Views to Verify Trips
# ORIGINAL SUBWAY DATA
subway_data.2 %>% filter(realtime_trip_id == 3300 & stop_mta_id == "120S" | realtime_trip_id == 3327 & stop_mta_id == "131S") %>% View("subway_data 3300")
# NEW DATA FRAME DATA
new_df %>% filter(start_trip_id == 3300) %>% View("new_df 3300")

test_df <- compute_itenerary_pair("2", "1", "120S", "127S", "127S", "131S", start_time)
# TODO: figure out multiple transfers with multiple lists

# PSEUDOCODE
# # NOTE: adding third train to the loop
# # parsing two rows for each train 
# i = 1
# j = 1
# k = 1
# counter_list <- c(i,j,k)


# TEST DATA

trains <- c("1", "2", "L")

stop_station <- list(c("120S", "127S"),
                      c("127S", "132S"),
                      c("L02S", "L06S"))



# create data frame that we're going to use
# test <- data.frame("itin_id" = c("1","1","1"), 
#                    "station"= c("120S", "127S","127S", "132S", "L02S", "L06S"),
#                    "line" = c("1", "1","2","2","L","L"))
```
### Multi-leg trip itinerary evaluation

```{r test-chunk}

# Helper Function to Determine if Day is Weekend
isWeekend <- function(day_of_week) {
  ifelse(day_of_week == "Saturday" | day_of_week == "Sunday", T, F)
}

# Helper Function To Get Leg Data
get_leg_data <- function(lines, start, end, start_time) {
  
  lines_list <- first(strsplit(lines, split = "_"))
  leg_data <- subway_data.2 %>%
    filter(stop_mta_id == start | stop_mta_id == end,
           route_mta_id %in% lines_list,
           departure_time > start_time) %>%
    mutate(day_of_week = weekdays((departure_time)),
           hour = hour(departure_time)) %>%
    filter(isWeekend(day_of_week) == F, hour > 6, hour < 20) %>%
    group_by(realtime_trip_id) %>%
    mutate(start_time = min(departure_time)) %>%
    filter(n() >= 2, stop_mta_id == end) %>%
    ungroup() %>%
    arrange(arrival_time)
  
  return(leg_data)
  
}





get_itinerary_times <- function(itinerary, start_time) {
  
  # handle the initial transfer special case
  transfer_special_case <- itinerary %>% filter(leg == 0)
  print(transfer_special_case$weight)
  transfer_time <- ifelse(nrow(transfer_special_case) == 0, 0, as.integer(transfer_special_case$weight))
  
  # handle final transfer special case
  end_transfer_special_case <- itinerary %>% filter(event == "end_trip", direction == "T")
  
  curr_itin <- itinerary %>% anti_join(transfer_special_case) %>% anti_join(end_transfer_special_case)
  print(nrow(curr_itin))
  
  end_transfer_time <- ifelse(nrow(end_transfer_special_case) == 0, 0, as.integer(last(curr_itin$weight)))
  
  # adjust the start time to take into account that transfer time
  adjusted_start <- as.POSIXct(start_time, origin = "1970-01-01", tz = "UTC") +
    as.integer(transfer_time)
  print(adjusted_start)
  
  trains <- curr_itin %>% .$line %>% unique()
  # print(length(trains))
  stops_data <- curr_itin %>% select(leg, stop_station) %>% split(.$leg)
  stop_station <- list()
  
  len_trains <- length(trains)
  # populate our stop_station list
  for (i in 1:len_trains) {
    stop_station[[i]] <- c(stops_data[[i]]$stop_station[1], stops_data[[i]]$stop_station[2])
  }
  print(stop_station)
  
  # list of train data frames
  train_data <- list()
  
  for (i in 1:len_trains) {
    start <- stop_station[[i]][1]
    end <- stop_station[[i]][2]
    lines <- trains[i]
    
    leg_data <- get_leg_data(lines, start, end, adjusted_start)
    
    # NOTE: DEBUG CODE
    # print(nrow(leg_data))
    
    # append to list
    train_data[[i]] <- leg_data
  }
  
  num_trains <- nrow(train_data[[1]])
  
  output_df <- data.frame(d=numeric(num_trains))
  # format output_df with appropriate columns
  for (i in 1:len_trains) {
    train <- trains[i]
    output_df[[paste('leg', i, '_line', sep='')]] <- character(num_trains)
    output_df[[paste('leg', i, '_trip_id',  sep='')]] <- numeric(num_trains)
    output_df[[paste('leg', i, '_start_time', sep='')]] <- numeric(num_trains)
    output_df[[paste('leg', i, '_end_time', sep='')]] <- numeric(num_trains)
  }
  
  output_df <- subset(output_df, select = -c(d))
  
  i <- 1
  row_info <- list()
  
  # NOTE: DEBUG CODE
  # start.time <- Sys.time()
  
  counters <- rep(1, len_trains)
  
  # set up flags
  no_more_trips <- F
  waited_too_long <- F
  
  
  
  while (i <= num_trains) {
    end_time <- train_data[[1]]$departure_time[i]
    row_info <- c(row_info,
                  as.character(train_data[[1]]$route_mta_id[i]),
                  train_data[[1]]$realtime_trip_id[i],
                  train_data[[1]]$start_time[i],
                  end_time)
    
    if (len_trains > 1) {
      for (ii in 2:len_trains) {
         start_transfer_time <- itinerary %>% filter(event == 'start_transfer' , leg == ii-1)
        
        # NOTE: DEBUG CODE
        # print(sprintf("ii = %d", ii))
        # print(train_data[[ii]]$realtime_trip_id[counters[ii]])
        # print(train_data[[ii]]$departure_time[counters[ii]])
        # print(end_time)
        while ((counters[ii] <= nrow(train_data[[ii]])) &
               (train_data[[ii]]$start_time[counters[ii]] < end_time + as.integer(start_transfer_time$weight[ii-1]))) {
          # NOTE: DEBUG CODE
          # print(sprintf("counters[ii] = ", counters[ii]))
          # print(sprintf("skipping train %s on leg %d", train_data[[ii]]$realtime_trip_id[counters[ii]], ii))
          counters[ii] = counters[ii] + 1
        }
        
        curr_idx <- counters[ii]
        
        # break out if this train_data doesn't exist
        if(is.na(train_data[[ii]]$departure_time[curr_idx])) {
          no_more_trips <- T
          break
        }
        
        # Added condition here to ignore trips where you wait at a station for more than an hour
        if(train_data[[ii]]$departure_time[curr_idx] > end_time + 3600) {
          waited_too_long <- T
          break
        }
        
        end_time <- train_data[[ii]]$departure_time[curr_idx]
        row_info <- c(row_info,
                      as.character(train_data[[ii]]$route_mta_id[curr_idx]),
                      train_data[[ii]]$realtime_trip_id[curr_idx],
                      train_data[[ii]]$start_time[curr_idx],
                      end_time)
        
        # NOTE: DEBUG CODE
        # print(sprintf("Leg #%s\n", ii))
        # print(row_info)
      }
    }
    
    
    if (no_more_trips == T) {
      output_df[i, ] <- NA
    } else if (waited_too_long == T) {
      output_df[i, ] <- NA
      # do nothing
      waited_too_long = F
    } else {
      output_df[i, ] <- row_info
    }
    row_info <- list()
    # increment i
    i = i + 1
  }
  
  output_df <- na.omit(output_df)
  
  for (i in 1:len_trains) {
    train <- trains[i]
    output_df[[paste('leg', i, '_start_time', sep='')]] <- as.POSIXct(output_df[[paste('leg', i, '_start_time', sep='')]],
                                                                      origin = "1970-01-01", tz = "UTC")
    output_df[[paste('leg', i, '_end_time', sep='')]] <- as.POSIXct(output_df[[paste('leg', i, '_end_time', sep='')]],
                                                                    origin = "1970-01-01", tz = "UTC")
  }
  
  output_df$time_diff <- output_df[, ncol(output_df)] - as.POSIXct(start_time, origin = "1970-01-01", tz = "UTC")
  output_df$given_start_time <- as.POSIXct(start_time, origin = "1970-01-01", tz = "UTC")
  output_df$adjusted_end_time <- output_df[, ncol(output_df) - 2] + end_transfer_time
  
  # filter out the beginning ti
  
  return(output_df)
}


# TEST DATA for itinerary

# test_data <- read_csv('../../data/sample_itinerary.csv')
test_data <- read_csv('20180723_edge_case_sample_itinerary.csv')

# filter out event and adding direction to station id  
test_train <- test_data %>% 
  filter(event != "travel") %>%
  mutate(stop_station = paste(station, direction, sep=''))

# TODO: UNCOMMENT WHEN ALL SPECIAL CASES RESOLVED
# itin_max <- max(test_train$itinerary_id)
# result <- vector ("list", length = itin_max)
# # test_stops <- list()
# 
# for (i in 1:itin_max) { 
#   itin <- test_train %>% filter(itinerary_id == i)
#   result[[i]] <- get_itinerary_times(itin, start_time = "2018-01-20 09:30:00") 
#   print(result[[i]])
# }

# remove any unused rows

test_itin <- test_train %>% filter(itinerary_id == 2)
test_df <- get_itinerary_times(test_itin, start_time = "2018-01-22 09:30:00")

#end.time <- Sys.time()
#time.taken <- end.time - start.time
#time.taken

# NOTE: DEBUG PLOT - show all trains individually on plot

filtered_test_df <- test_df %>% filter(hour(leg1_start_time) >= 8 & hour(leg1_start_time) <= 9) 


# plot_data <- bind_rows(train_data[[1]], train_data[[2]], train_data[[3]])
# plot_data %>% filter(month(start_time) == 2 & day(start_time) == 16 & hour(start_time) > 19 & hour(start_time) < 24) %>%
#   arrange(start_time) %>%
#   mutate(itin = row_number()) %>%
#   ggplot(aes(color = route_mta_id)) +
#   geom_segment(aes(x = start_time, xend = departure_time, y = itin, yend = itin)) +
#   geom_text(aes(label = realtime_trip_id, x = start_time, y = itin))

# ITINERARY PLOT
# filtered_test_df %>% mutate(itin = row_number()) %>%
#   filter(itin <= 5) %>%
#   ggplot() +
#     geom_segment(aes(x = leg1_start_time, xend = leg1_end_time, y = itin, yend = itin), color = 'red') +
#     geom_segment(aes(x = leg2_start_time, xend = leg2_end_time, y = itin, yend = itin), color = 'blue') +
#     geom_segment(aes(x = leg3_start_time, xend = leg3_end_time, y = itin, yend = itin), color = 'green') +
#     geom_text(aes(label = leg1_trip_id, x = leg1_start_time, y = itin), color = "red") +
#     geom_text(aes(label = leg2_trip_id, x = leg2_start_time, y = itin), color = "blue") +
#     geom_text(aes(label = leg3_trip_id, x = leg3_start_time, y = itin), color = "green") + 
#     ylim(c(0, 10))

filtered_test_df %>% ggplot() +
  geom_histogram(aes(x = time_diff))

# PSUEDOCODE
# list of start_times 
# for (x in counter_list) {
#  add start_time_column to list of start times
#  add end_time_column to list of end times
#  add train_id column to list of train ids
# }
# 
# data is a list of dataframes, where data[i] corresponds to the ith train in the itinerary
# 
# while (i < nrow(leg_1_data)) {
#   record when train i leaves
#   record when train i arrives
#   store for train i
#   
#   for ii in range(2, len(counter_list)+1) {
#       while data[ii][counter_list[ii]] < start_time!!!! {
#           counter_list[ii] += 1
#       }
#       
#       record when train ii leaves
#       record when train ii arrives
#       record when train ii departs
#   }
#       
# }



```